Feature googlemaps
liorsinai-bbd/TravelManager pull request #3
Opened 2021-04-20 16:52 UTC by liorsinai-bbd

GPS location information from the Google Maps API
- get GPS latitude and longitude
- get distance between elements
- download a static Mercator map image with markers

2021-04-20 18:57 UTC, KirstenMack commented on src/main/java/za/co/bbdgrads/TravelManager/Location/DemoMaps.java
> +        }
@liorsinai-bbd, Is there a reason there are two catches? :

2021-04-20 18:57 UTC, KirstenMack commented on src/main/java/za/co/bbdgrads/TravelManager/Location/DemoMaps.java
> +        GeoApiContext context = new GeoApiContext.Builder().apiKey(apikey).build();
I feel like these two lines are a repeat of what occurs in lines 41-45, and 114-118. 
Should we refactor this into its own function, or is it too few lines of code to warrant that?

2021-04-20 18:57 UTC, KirstenMack commented on src/main/java/za/co/bbdgrads/TravelManager/Location/GoogleMapsApiService.java
> +    public static DistanceElement getDistanceBetweenLocations(String destination, String origin) throws Exception{
Does this just raise a general exception?

2021-04-20 18:57 UTC, KirstenMack commented on src/main/java/za/co/bbdgrads/TravelManager/Location/LocationManager.java
> +    public static void downloadStaticMap(String[] addresses){
Where is this used? I can't seem to find it.

2021-04-20 18:57 UTC, KirstenMack commented on src/main/java/za/co/bbdgrads/TravelManager/Location/LocationManager.java
> +
1. Is there a reason for the indentation?
2.  Is there a reason for the different implementations of the "destination" object, being a LocationObject, and "origin" simply being a LatLng object? Their functionality appears the same here so just checking if I am missing something.

2021-04-20 19:22 UTC, liorsinai-bbd commented on src/main/java/za/co/bbdgrads/TravelManager/Location/DemoMaps.java
> +        }
Since I am handling both exceptions the same way, no good reason here 😅

2021-04-20 19:24 UTC, liorsinai-bbd commented on src/main/java/za/co/bbdgrads/TravelManager/Location/DemoMaps.java
> +        GeoApiContext context = new GeoApiContext.Builder().apiKey(apikey).build();
Definitely think it's too few lines.

2021-04-20 19:25 UTC, liorsinai-bbd commented on src/main/java/za/co/bbdgrads/TravelManager/Location/LocationManager.java
> +    public static void downloadStaticMap(String[] addresses){
LocationManager

2021-04-20 19:26 UTC, liorsinai-bbd commented on src/main/java/za/co/bbdgrads/TravelManager/Location/LocationManager.java
> +
1. the indention isn't supposed to be there
2. you're right, I'm not consistent here

2021-04-20 19:30 UTC, liorsinai-bbd commented on src/main/java/za/co/bbdgrads/TravelManager/Location/GoogleMapsApiService.java
> +    public static DistanceElement getDistanceBetweenLocations(String destination, String origin) throws Exception{
It throws 2 types of exceptions actually, InterruptedException and IOException. 
I've bundled them into one so they're handled the same.
Not sure if we should handle them differently?

2021-04-20 19:32 UTC, liorsinai-bbd commented on src/main/java/za/co/bbdgrads/TravelManager/Location/LocationManager.java
> +    public static void downloadStaticMap(String[] addresses){
Oh there's a main function I didn't include in the commits:
```	
public static void main(String[] args) {
		DemoMaps.demoStaticMap();
		LocationManager.printDistances("BBD, Johannesburg, South Africa", "Kruger National Park, South Africa");

		// make map
		String[] addresses = {
			"BBD, Johannesburg, South Africa",
			"Cape Town, South Africa",
			"Maldives",
			"Kruger National Park"
		};
		LocationManager.downloadStaticMap(addresses);
	}
```

2021-04-20 19:59 UTC, KirstenMack requested changes

2021-04-20 19:59 UTC, KirstenMack commented on src/main/java/za/co/bbdgrads/TravelManager/Location/DemoMaps.java
> +        }
lol okay, please remove the duplicate

2021-04-20 19:59 UTC, KirstenMack commented on src/main/java/za/co/bbdgrads/TravelManager/Location/GoogleMapsApiService.java
> +    public static DistanceElement getDistanceBetweenLocations(String destination, String origin) throws Exception{
I'm not sure either, but maybe it would be more clear?

2021-04-20 19:59 UTC, KirstenMack commented on src/main/java/za/co/bbdgrads/TravelManager/Location/LocationManager.java
> +
Please will you fix up the above

2021-04-20 19:59 UTC, KirstenMack commented on src/main/java/za/co/bbdgrads/TravelManager/Location/LocationManager.java
> +    public static void downloadStaticMap(String[] addresses){
Cool, please commit that for us :)

2021-04-21 15:55 UTC, laurenm-bbd commented on src/main/java/za/co/bbdgrads/TravelManager/Location/GoogleMapsApiService.java
> +    public static DistanceElement getDistanceBetweenLocations(String destination, String origin) throws Exception{
I agree, I think rather name the 2 exceptions explicitly than throw a general exception?

2021-04-22 09:57 UTC, merged